### ISSUE TITLE
Get cannot read property of undefined error on first run

### ISSUE THREAD

**Issue by TimothyBJacobs** [cedaro/node-wp-i18n#10]
When I run the makepot command for the first time, or when the target pot file doesn't exist, I get the following error. The pot file still generates, and appears to be correct, but the error does occur.

```bash
run wpi18n makepot --type=wp-plugin --pot-file="./php.pot"
```

```
Unhandled rejection TypeError: Cannot read property 'content-type' of undefined
    at normalizeForComparison (MY_PATH/node_modules/node-wp-i18n/lib/pot.js:54:48)
    at Pot.sameAs (MY_PATH/node_modules/node-wp-i18n/lib/pot.js:166:32)
    at MY_PATH/node_modules/node-wp-i18n/lib/makepot.js:92:43
    at tryCatcher (MY_PATH/node_modules/node-wp-i18n/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (MY_PATH/node_modules/node-wp-i18n/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (MY_PATH/node_modules/node-wp-i18n/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (MY_PATH/node_modules/node-wp-i18n/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (MY_PATH/node_modules/node-wp-i18n/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (MY_PATH/node_modules/node-wp-i18n/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (MY_PATH/node_modules/node-wp-i18n/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (MY_PATH/node_modules/node-wp-i18n/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

When I started looking around, it seemed like the third time `normalizeForComparison()` was called, it was called with an empty string. The pot object in `sameAs` looks like.

```
Pot {
  isOpen: false,
  filename: 'MY_PATH/lang/php.pot',
  contents: '',
  initialDate: '',
  fingerprint: '' }
```

It seems like if the pot file has an empty contents, that function could return false before normalizing the file. Thoughts?

**Comment by bradyvercher** [comment]
Good catch, @TimothyBJacobs. Yeah, if `normalizeForComparison()` receives an empty value for the argument, it should probably just return the argument instead of trying to process it.
